sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=pep8
    - python: "3.6"
      env: TOXENV=docs
cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox
language: python
script:
  - tox
notifications:
  email: false
